server:
  ip: localhost
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/a_cook?serverTimezone=GMT%2b8
    username: root
    password: 2013400236
  # ====================== 139邮箱配置（已改好） ======================
  mail:
    host: smtp.139.com
    port: 465
    username: xiyueforum0425@139.com
    password: 975cfe07b829bbe5cf00
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  # ====================================================================
  redis:
    host: 127.0.0.1
    port: 6379
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: D:/uploadPath/files/